//! CUDA runtime for the generic active-prefix reduced-SWIRL wrapper.
//!
//! This is the CUDA counterpart of `reduced_swirl_wrapper_system`.  It keeps
//! one setup-fixed wrapper circuit, uses OpenVM's CUDA preprocessed committer
//! for required-AIR key generation, accepts device-resident component traces
//! with repeated component AIR IDs, and emits one ordinary MultiSTARK proof.
//! The three small wrapper-core traces are generated by the CPU reference and
//! uploaded once; component traces are neither downloaded nor regenerated.
//!
//! The CPU verifier is the proof-system anchor.  Every CUDA proof is checked
//! against the exact key and public values before this API returns it.

use core::mem::size_of;
use std::sync::Arc;

use openvm_continuations::circuit::reduced_swirl_warp::{
    generate_reduced_swirl_wrapper_core_traces, ReducedSwirlWrapperBinding,
    ReducedSwirlWrapperCircuit, ReducedSwirlWrapperRecord, ReducedSwirlWrapperVerifierComponents,
};
use openvm_cpu_backend::CpuBackend;
use openvm_cuda_backend::{
    BabyBearPoseidon2GpuEngine, GpuBackend, GpuDevice, GpuPreprocessedCommitter,
};
use openvm_stark_backend::{
    keygen::{
        types::{MultiStarkProvingKey, MultiStarkVerifyingKey},
        MultiStarkKeygenBuilder,
    },
    p3_matrix::Matrix,
    proof::Proof,
    prover::{
        AirProvingContext, CommittedTraceData, DeviceDataTransporter, DeviceMultiStarkProvingKey,
        MatrixDimensions, ProverBackend, ProvingContext, TraceCommitter,
    },
    StarkEngine, SystemParams,
};
use openvm_stark_sdk::config::baby_bear_poseidon2::{
    BabyBearPoseidon2CpuEngine, Digest, DuplexSponge, F,
};
use openvm_verify_stark_host::pvs::{VerifierBasePvs, VmPvs};

use super::reduced_swirl_wrapper_system::{
    ReducedSwirlWrapperSystem, ReducedSwirlWrapperSystemError, ReducedSwirlWrapperWitness,
};
use crate::SC;

type CpuEngine = BabyBearPoseidon2CpuEngine<DuplexSponge>;

/// Setup-fixed CUDA wrapper system.
///
/// The parameters are retained beside the CPU reference system because the
/// latter deliberately keeps them private.  Constructing both in this one
/// function prevents a CUDA key from being generated under caller-supplied
/// parameters that differ from the system's intended parameters.
pub struct ReducedSwirlWrapperCudaSystem<C: ReducedSwirlWrapperVerifierComponents> {
    reference: Arc<ReducedSwirlWrapperSystem<C>>,
    params: SystemParams,
    /// Setup-fixed map from keyed component slots to logical component AIRs.
    /// Repetitions reuse an AIR definition but receive distinct MultiSTARK AIR
    /// IDs, as required by the ordinary proof and CPU verifier formats.
    component_air_profile: Vec<usize>,
}

impl<C: ReducedSwirlWrapperVerifierComponents> ReducedSwirlWrapperCudaSystem<C> {
    pub fn new(
        binding: ReducedSwirlWrapperBinding,
        components: Arc<C>,
        params: SystemParams,
    ) -> Result<Self, ReducedSwirlWrapperSystemError> {
        let component_air_profile = (0..components.component_air_count()).collect();
        Self::new_with_component_air_profile(binding, components, params, component_air_profile)
    }

    /// Construct a setup-fixed wrapper whose component slots may reuse logical
    /// component AIR definitions.
    ///
    /// OpenVM's ordinary MultiSTARK proof has one `TraceVData` entry per keyed
    /// AIR ID. Therefore several traces cannot soundly be represented by
    /// repeating one keyed ID in `ProvingContext`. Instead, each occurrence in
    /// this profile receives a distinct required key slot while evaluating the
    /// selected logical AIR. The profile is authenticated by the VK pre-hash
    /// and checked again when keys and witnesses are consumed.
    pub fn new_with_component_air_profile(
        binding: ReducedSwirlWrapperBinding,
        components: Arc<C>,
        params: SystemParams,
        component_air_profile: Vec<usize>,
    ) -> Result<Self, ReducedSwirlWrapperSystemError> {
        let reference = Arc::new(ReducedSwirlWrapperSystem::new(
            binding,
            components,
            params.clone(),
        )?);
        let system = Self {
            reference,
            params,
            component_air_profile,
        };
        system.validate_air_inventory()?;
        Ok(system)
    }

    #[must_use]
    pub fn binding(&self) -> &ReducedSwirlWrapperBinding {
        self.reference.binding()
    }

    #[must_use]
    pub fn reference_system(&self) -> Arc<ReducedSwirlWrapperSystem<C>> {
        Arc::clone(&self.reference)
    }

    #[must_use]
    pub fn circuit(&self) -> Arc<ReducedSwirlWrapperCircuit<C>> {
        self.reference.circuit()
    }

    #[must_use]
    pub fn component_air_count(&self) -> usize {
        self.component_air_profile.len()
    }

    /// Number of distinct logical component AIR definitions.
    #[must_use]
    pub fn component_relation_count(&self) -> usize {
        self.reference.component_air_count()
    }

    /// Setup-fixed logical component ID for every keyed component slot.
    #[must_use]
    pub fn component_air_profile(&self) -> &[usize] {
        &self.component_air_profile
    }

    #[must_use]
    pub fn airs(&self) -> Vec<openvm_stark_backend::AirRef<SC>> {
        let base = self.reference.airs();
        let mut airs = Vec::with_capacity(3 + self.component_air_count());
        airs.extend(base[..3].iter().cloned());
        airs.extend(
            self.component_air_profile
                .iter()
                .map(|&logical_id| Arc::clone(&base[logical_id + 3])),
        );
        airs
    }

    fn validate_air_inventory(&self) -> Result<(), ReducedSwirlWrapperSystemError> {
        self.binding()
            .validate()
            .map_err(ReducedSwirlWrapperSystemError::Binding)?;
        let relation_count = self.component_relation_count();
        if self.component_air_profile.is_empty()
            || relation_count == 0
            || self
                .component_air_profile
                .iter()
                .any(|&logical_id| logical_id >= relation_count)
            || (0..relation_count)
                .any(|logical_id| !self.component_air_profile.contains(&logical_id))
        {
            return Err(ReducedSwirlWrapperSystemError::KeyIntegrity(
                "component AIR profile",
            ));
        }
        let expected = 3usize.checked_add(self.component_air_count()).ok_or(
            ReducedSwirlWrapperSystemError::KeyIntegrity("AIR count overflow"),
        )?;
        let airs = self.airs();
        if airs.len() != expected
            || airs.first().map(|air| air.num_public_values())
                != Some(size_of::<VerifierBasePvs<u8>>())
            || airs.get(1).map(|air| air.num_public_values()) != Some(size_of::<VmPvs<u8>>())
            || airs
                .get(2..)
                .is_none_or(|airs| airs.iter().any(|air| air.num_public_values() != 0))
        {
            return Err(ReducedSwirlWrapperSystemError::KeyIntegrity(
                "AIR inventory",
            ));
        }
        Ok(())
    }

    fn keygen_cuda(
        &self,
        device: &GpuDevice,
    ) -> Result<ReducedSwirlWrapperCudaKeys, ReducedSwirlWrapperSystemError> {
        self.validate_air_inventory()?;
        let config = SC::default_from_params(self.params.clone());
        let mut builder = MultiStarkKeygenBuilder::with_preprocessed_committer(
            config,
            Arc::new(GpuPreprocessedCommitter::new(device)),
        );
        // This is one fixed verifier relation.  Optional AIRs would permit a
        // prover to omit a self-balanced receipt subgraph, so every setup slot
        // is required. Repeated logical AIRs already have distinct keyed IDs.
        for air in self.airs() {
            builder.add_required_air(air);
        }
        let proving_key = builder
            .generate_pk()
            .map_err(|error| ReducedSwirlWrapperSystemError::Keygen(error.to_string()))?;
        let verifying_key = proving_key.get_vk();
        let keys = ReducedSwirlWrapperCudaKeys {
            binding: self.binding().clone(),
            component_air_profile: self.component_air_profile.clone(),
            proving_key: Arc::new(proving_key),
            verifying_key: Arc::new(verifying_key),
        };
        validate_keys(self, &keys)?;
        Ok(keys)
    }
}

/// Host-owned key material for one exact CUDA wrapper inventory.
///
/// The private binding and AIR profile prevent constructing a key-authority
/// token from an unrelated MultiSTARK key.  `from_keys` still revalidates all
/// metadata, key hashes, required flags, and AIR geometry.
#[derive(Clone)]
pub struct ReducedSwirlWrapperCudaKeys {
    binding: ReducedSwirlWrapperBinding,
    component_air_profile: Vec<usize>,
    proving_key: Arc<MultiStarkProvingKey<SC>>,
    verifying_key: Arc<MultiStarkVerifyingKey<SC>>,
}

impl ReducedSwirlWrapperCudaKeys {
    #[must_use]
    pub fn binding(&self) -> &ReducedSwirlWrapperBinding {
        &self.binding
    }

    #[must_use]
    pub fn component_air_profile(&self) -> &[usize] {
        &self.component_air_profile
    }

    #[must_use]
    pub fn proving_key(&self) -> Arc<MultiStarkProvingKey<SC>> {
        Arc::clone(&self.proving_key)
    }

    #[must_use]
    pub fn verifying_key(&self) -> Arc<MultiStarkVerifyingKey<SC>> {
        Arc::clone(&self.verifying_key)
    }
}

/// Reusable CUDA MultiSTARK prover for the complete reduced-SWIRL wrapper.
pub struct ReducedSwirlWrapperCudaProver<C: ReducedSwirlWrapperVerifierComponents> {
    system: Arc<ReducedSwirlWrapperCudaSystem<C>>,
    keys: ReducedSwirlWrapperCudaKeys,
    device_key: DeviceMultiStarkProvingKey<GpuBackend>,
    engine: BabyBearPoseidon2GpuEngine,
}

impl<C: ReducedSwirlWrapperVerifierComponents> ReducedSwirlWrapperCudaProver<C> {
    pub fn new(
        system: Arc<ReducedSwirlWrapperCudaSystem<C>>,
    ) -> Result<Self, ReducedSwirlWrapperSystemError> {
        let mut engine = BabyBearPoseidon2GpuEngine::new(system.params.clone());
        // Recursive verifier AIRs contain deep expression DAGs.  The canonical
        // evaluator avoids host-side monomial expansion without changing the
        // AIR, proof transcript, or verifier.
        engine.device_mut().prover_config_mut().compile_monomials = wrapper_compile_monomials();
        let keys = system.keygen_cuda(engine.device())?;
        Self::from_keys_and_engine(system, keys, engine)
    }

    pub fn from_keys(
        system: Arc<ReducedSwirlWrapperCudaSystem<C>>,
        keys: ReducedSwirlWrapperCudaKeys,
    ) -> Result<Self, ReducedSwirlWrapperSystemError> {
        validate_keys(system.as_ref(), &keys)?;
        let mut engine = BabyBearPoseidon2GpuEngine::new(keys.proving_key.params.clone());
        engine.device_mut().prover_config_mut().compile_monomials = wrapper_compile_monomials();
        Self::from_keys_and_engine(system, keys, engine)
    }

    fn from_keys_and_engine(
        system: Arc<ReducedSwirlWrapperCudaSystem<C>>,
        keys: ReducedSwirlWrapperCudaKeys,
        engine: BabyBearPoseidon2GpuEngine,
    ) -> Result<Self, ReducedSwirlWrapperSystemError> {
        validate_keys(system.as_ref(), &keys)?;
        let prepared = <GpuDevice as DeviceDataTransporter<SC, GpuBackend>>::prepare_pk_for_device(
            engine.device(),
            keys.proving_key.as_ref(),
        );
        let device_key =
            <GpuDevice as DeviceDataTransporter<SC, GpuBackend>>::transport_prepared_pk_to_device(
                engine.device(),
                keys.proving_key.as_ref(),
                prepared,
            );
        Ok(Self {
            system,
            keys,
            device_key,
            engine,
        })
    }

    #[must_use]
    pub fn keys(&self) -> &ReducedSwirlWrapperCudaKeys {
        &self.keys
    }

    #[must_use]
    pub fn device(&self) -> &GpuDevice {
        self.engine.device()
    }

    /// Borrow the exact engine that owns the wrapper proving key.  Production
    /// source trace generation uses this to create verifier tables directly
    /// on the same CUDA device and stream domain instead of staging them in
    /// host memory.
    #[must_use]
    pub fn engine(&self) -> &BabyBearPoseidon2GpuEngine {
        &self.engine
    }

    /// Prove one complete wrapper record from already resident component
    /// contexts. Repeated logical component AIR IDs are assigned to their
    /// setup-fixed keyed slots in stable per-ID order; every configured slot
    /// must be supplied exactly once.
    pub fn prove(
        &mut self,
        record: &ReducedSwirlWrapperRecord,
        witness: ReducedSwirlWrapperWitness<GpuBackend>,
    ) -> Result<Proof<SC>, ReducedSwirlWrapperSystemError> {
        validate_keys(self.system.as_ref(), &self.keys)?;
        let (context, expected) =
            assemble_cuda_context(self.system.as_ref(), self.engine.device(), record, witness)?;
        #[cfg(debug_assertions)]
        if std::env::var("OPENVM_SKIP_DEBUG") != Ok(String::from("1")) {
            self.engine.debug(&self.system.airs(), &context);
        }
        let proof = self
            .engine
            .prove(&self.device_key, context)
            .map_err(|error| ReducedSwirlWrapperSystemError::Prover(error.to_string()))?;
        validate_public_values(&expected, &proof.public_values)?;
        cpu_verify(self.keys.verifying_key.as_ref(), &proof)?;
        Ok(proof)
    }

    /// Verify with the ordinary CPU MultiSTARK verifier and exact wrapper
    /// public values. This is also run automatically by [`Self::prove`].
    pub fn verify(
        &self,
        record: &ReducedSwirlWrapperRecord,
        proof: &Proof<SC>,
    ) -> Result<(), ReducedSwirlWrapperSystemError> {
        validate_keys(self.system.as_ref(), &self.keys)?;
        let expected = expected_public_values(self.system.as_ref(), record)?;
        validate_public_values(&expected, &proof.public_values)?;
        cpu_verify(self.keys.verifying_key.as_ref(), proof)
    }
}

/// Monomial compilation is useful as a differential diagnostic for the CUDA
/// expression-DAG path. Production remains DAG-only unless explicitly
/// requested because recursive verifier relations can otherwise require very
/// large host-side expansion.
fn wrapper_compile_monomials() -> bool {
    std::env::var("OPENVM_WARP_WRAPPER_COMPILE_MONOMIALS").as_deref() == Ok("1")
}

pub fn prove_reduced_swirl_wrapper_cuda<C>(
    prover: &mut ReducedSwirlWrapperCudaProver<C>,
    record: &ReducedSwirlWrapperRecord,
    witness: ReducedSwirlWrapperWitness<GpuBackend>,
) -> Result<Proof<SC>, ReducedSwirlWrapperSystemError>
where
    C: ReducedSwirlWrapperVerifierComponents,
{
    prover.prove(record, witness)
}

/// Upload an authenticated CPU component witness exactly once for the direct
/// CUDA wrapper proof.
///
/// Common traces are transferred without reconstruction. Cached traces are
/// recommitted once on the destination device because CPU and CUDA PCS-data
/// carriers differ; equality with the CPU commitment rejects orientation,
/// parameter, or transport mistakes. Equal cached roots with equal geometry
/// share one resident allocation.
pub fn transport_reduced_swirl_wrapper_witness_to_cuda(
    device: &GpuDevice,
    witness: ReducedSwirlWrapperWitness<CpuBackend<SC>>,
) -> Result<ReducedSwirlWrapperWitness<GpuBackend>, ReducedSwirlWrapperSystemError> {
    let component_contexts =
        transport_reduced_swirl_wrapper_contexts_to_cuda(device, witness.component_contexts)?;
    Ok(ReducedSwirlWrapperWitness { component_contexts })
}

/// Upload an arbitrary indexed subset of wrapper component contexts.  This
/// permits the large source verifier to remain device-resident while the
/// compact VACC and terminal contexts still use their audited CPU trace
/// generators.
pub fn transport_reduced_swirl_wrapper_contexts_to_cuda(
    device: &GpuDevice,
    contexts: Vec<(usize, AirProvingContext<CpuBackend<SC>>)>,
) -> Result<Vec<(usize, AirProvingContext<GpuBackend>)>, ReducedSwirlWrapperSystemError> {
    struct CachedUpload {
        commitment: Digest,
        width: usize,
        height: usize,
        committed: CommittedTraceData<GpuBackend>,
    }

    let mut cached_uploads = Vec::<CachedUpload>::new();
    let mut component_contexts = Vec::with_capacity(contexts.len());
    for (air, context) in contexts {
        let AirProvingContext {
            cached_mains,
            common_main,
            public_values,
        } = context;
        let common_main =
            <GpuDevice as DeviceDataTransporter<SC, GpuBackend>>::
                transport_row_major_matrix_to_device(device, &common_main);
        let mut device_cached = Vec::with_capacity(cached_mains.len());
        for cached in cached_mains {
            let width = Matrix::width(&cached.trace);
            let height = Matrix::height(&cached.trace);
            if let Some(existing) = cached_uploads.iter().find(|existing| {
                existing.commitment == cached.commitment
                    && existing.width == width
                    && existing.height == height
            }) {
                device_cached.push(existing.committed.clone());
                continue;
            }
            if cached_uploads
                .iter()
                .any(|existing| existing.commitment == cached.commitment)
            {
                return Err(ReducedSwirlWrapperSystemError::Context(
                    "cached commitment reused with different geometry",
                ));
            }
            let trace = <GpuDevice as DeviceDataTransporter<SC, GpuBackend>>::
                transport_row_major_matrix_to_device(device, &cached.trace);
            let (commitment, data) =
                <GpuDevice as TraceCommitter<GpuBackend>>::commit(device, &[&trace]).map_err(
                    |error| {
                        ReducedSwirlWrapperSystemError::Prover(format!(
                            "CUDA cached-main commitment: {error}"
                        ))
                    },
                )?;
            if commitment != cached.commitment {
                return Err(ReducedSwirlWrapperSystemError::Context(
                    "CPU/CUDA cached commitment mismatch",
                ));
            }
            let committed = CommittedTraceData {
                commitment,
                trace,
                data: Arc::new(data),
            };
            cached_uploads.push(CachedUpload {
                commitment,
                width,
                height,
                committed: committed.clone(),
            });
            device_cached.push(committed);
        }
        component_contexts.push((
            air,
            AirProvingContext::new(device_cached, common_main, public_values),
        ));
    }
    Ok(component_contexts)
}

fn validate_keys<C: ReducedSwirlWrapperVerifierComponents>(
    system: &ReducedSwirlWrapperCudaSystem<C>,
    keys: &ReducedSwirlWrapperCudaKeys,
) -> Result<(), ReducedSwirlWrapperSystemError> {
    system.validate_air_inventory()?;
    let expected = 3usize.checked_add(system.component_air_count()).ok_or(
        ReducedSwirlWrapperSystemError::KeyIntegrity("AIR count overflow"),
    )?;
    let config = SC::default_from_params(keys.verifying_key.inner.params.clone());
    if keys.binding != *system.binding()
        || keys.component_air_profile != system.component_air_profile
        || keys.proving_key.params != system.params
        || keys.verifying_key.inner.params != system.params
        || keys.proving_key.per_air.len() != expected
        || keys.verifying_key.inner.per_air.len() != expected
        || keys.proving_key.vk_pre_hash != keys.verifying_key.pre_hash
        || !keys.verifying_key.has_consistent_pre_hash(&config)
    {
        return Err(ReducedSwirlWrapperSystemError::KeyIntegrity("wrapper key"));
    }

    let airs = system.airs();
    for (vk, air) in keys.verifying_key.inner.per_air.iter().zip(airs) {
        if !vk.is_required
            || vk.params.num_public_values != air.num_public_values()
            || vk.params.width.common_main != air.common_main_width()
            || vk.params.width.cached_mains != air.cached_main_widths()
        {
            return Err(ReducedSwirlWrapperSystemError::KeyIntegrity(
                "wrapper AIR key shape",
            ));
        }
    }
    Ok(())
}

fn expected_public_values<C: ReducedSwirlWrapperVerifierComponents>(
    system: &ReducedSwirlWrapperCudaSystem<C>,
    record: &ReducedSwirlWrapperRecord,
) -> Result<Vec<Vec<F>>, ReducedSwirlWrapperSystemError> {
    let circuit = system.circuit();
    let core = generate_reduced_swirl_wrapper_core_traces(
        system.binding(),
        circuit.components.receipt_buses(),
        record,
    )
    .map_err(ReducedSwirlWrapperSystemError::Binding)?;
    Ok(public_values_from_core(
        core.verifier_public_values,
        core.vm_public_values,
        system.component_air_count(),
    ))
}

fn public_values_from_core(
    verifier: Vec<F>,
    vm: Vec<F>,
    component_air_count: usize,
) -> Vec<Vec<F>> {
    let mut expected = vec![verifier, vm, Vec::new()];
    expected.resize_with(3 + component_air_count, Vec::new);
    expected
}

fn assemble_cuda_context<C: ReducedSwirlWrapperVerifierComponents>(
    system: &ReducedSwirlWrapperCudaSystem<C>,
    device: &GpuDevice,
    record: &ReducedSwirlWrapperRecord,
    witness: ReducedSwirlWrapperWitness<GpuBackend>,
) -> Result<(ProvingContext<GpuBackend>, Vec<Vec<F>>), ReducedSwirlWrapperSystemError> {
    validate_component_contexts(system, &witness.component_contexts)?;
    let circuit = system.circuit();
    let core = generate_reduced_swirl_wrapper_core_traces(
        system.binding(),
        circuit.components.receipt_buses(),
        record,
    )
    .map_err(ReducedSwirlWrapperSystemError::Binding)?;
    let expected = public_values_from_core(
        core.verifier_public_values.clone(),
        core.vm_public_values.clone(),
        system.component_air_count(),
    );
    let mut per_trace = vec![
        (
            0,
            AirProvingContext::new(
                Vec::new(),
                <GpuDevice as DeviceDataTransporter<SC, GpuBackend>>::
                    transport_row_major_matrix_to_device(device, &core.verifier_pvs),
                core.verifier_public_values,
            ),
        ),
        (
            1,
            AirProvingContext::new(
                Vec::new(),
                <GpuDevice as DeviceDataTransporter<SC, GpuBackend>>::
                    transport_row_major_matrix_to_device(device, &core.vm_pvs),
                core.vm_public_values,
            ),
        ),
        (
            2,
            AirProvingContext::new(
                Vec::new(),
                <GpuDevice as DeviceDataTransporter<SC, GpuBackend>>::
                    transport_row_major_matrix_to_device(device, &core.statement),
                Vec::new(),
            ),
        ),
    ];
    let mut by_logical_air = (0..system.component_relation_count())
        .map(|_| Vec::new())
        .collect::<Vec<Vec<AirProvingContext<GpuBackend>>>>();
    for (logical_air, context) in witness.component_contexts {
        by_logical_air[logical_air].push(context);
    }
    // Pop from the end after reversing to preserve the caller's order among
    // repeated contexts without moving or downloading their device matrices.
    for contexts in &mut by_logical_air {
        contexts.reverse();
    }
    for (slot, &logical_air) in system.component_air_profile.iter().enumerate() {
        let context =
            by_logical_air[logical_air]
                .pop()
                .ok_or(ReducedSwirlWrapperSystemError::Context(
                    "component AIR multiplicity profile",
                ))?;
        per_trace.push((slot + 3, context));
    }
    Ok((ProvingContext::new(per_trace), expected))
}

fn validate_component_contexts<C, PB>(
    system: &ReducedSwirlWrapperCudaSystem<C>,
    contexts: &[(usize, AirProvingContext<PB>)],
) -> Result<(), ReducedSwirlWrapperSystemError>
where
    C: ReducedSwirlWrapperVerifierComponents,
    PB: ProverBackend<Val = F>,
{
    let airs = system.reference.airs();
    let mut actual_multiplicities = vec![0usize; system.component_relation_count()];
    let mut expected_multiplicities = vec![0usize; system.component_relation_count()];
    for &logical_air in &system.component_air_profile {
        expected_multiplicities[logical_air] += 1;
    }
    for (component_air, context) in contexts {
        let air_id =
            component_air
                .checked_add(3)
                .ok_or(ReducedSwirlWrapperSystemError::Context(
                    "AIR index overflow",
                ))?;
        let air = airs
            .get(air_id)
            .ok_or(ReducedSwirlWrapperSystemError::Context("AIR index"))?;
        actual_multiplicities[*component_air] += 1;
        let common_height = context.common_main.height();
        if !context.public_values.is_empty()
            || context.common_main.width() != air.common_main_width()
            || context.cached_mains.len() != air.cached_main_widths().len()
            || common_height == 0
            || !common_height.is_power_of_two()
        {
            return Err(ReducedSwirlWrapperSystemError::Context("trace shape"));
        }
        for (cached, width) in context.cached_mains.iter().zip(air.cached_main_widths()) {
            if cached.trace.width() != width || cached.trace.height() != common_height {
                return Err(ReducedSwirlWrapperSystemError::Context(
                    "cached trace shape",
                ));
            }
        }
    }
    if actual_multiplicities != expected_multiplicities {
        return Err(ReducedSwirlWrapperSystemError::Context(
            "component AIR multiplicity profile",
        ));
    }
    Ok(())
}

fn validate_public_values(
    expected: &[Vec<F>],
    actual: &[Vec<F>],
) -> Result<(), ReducedSwirlWrapperSystemError> {
    if expected != actual {
        return Err(ReducedSwirlWrapperSystemError::PublicValues);
    }
    Ok(())
}

fn cpu_verify(
    key: &MultiStarkVerifyingKey<SC>,
    proof: &Proof<SC>,
) -> Result<(), ReducedSwirlWrapperSystemError> {
    CpuEngine::new(key.inner.params.clone())
        .verify(key, proof)
        .map_err(|error| ReducedSwirlWrapperSystemError::Verifier(error.to_string()))
}

#[cfg(test)]
mod tests {
    use openvm_continuations::circuit::reduced_swirl_warp::{
        ReducedSwirlSourceReceiptMessage, ReducedSwirlTerminalReceiptMessage,
        ReducedSwirlVaccReceiptMessage, ReducedSwirlWrapperReceiptBuses,
        ReducedSwirlWrapperStatement, REDUCED_SWIRL_WRAPPER_PROTOCOL_VERSION,
    };
    use openvm_cpu_backend::CpuBackend;
    use openvm_stark_backend::{
        interaction::InteractionBuilder,
        p3_air::{Air, AirBuilder, BaseAir},
        p3_field::{Field, PrimeCharacteristicRing, PrimeField32},
        p3_matrix::{dense::RowMajorMatrix, Matrix},
        AirRef, BaseAirWithPublicValues, PartitionedBaseAir, StarkProtocolConfig,
    };
    use openvm_stark_sdk::config::baby_bear_poseidon2::{Digest, DIGEST_SIZE};
    use openvm_verify_stark_host::pvs::VkCommit;

    use super::*;

    fn digest(seed: u32) -> Digest {
        core::array::from_fn(|index| F::from_u32(seed + index as u32))
    }

    fn binding() -> ReducedSwirlWrapperBinding {
        ReducedSwirlWrapperBinding {
            protocol_version: REDUCED_SWIRL_WRAPPER_PROTOCOL_VERSION,
            protocol_digest: digest(10),
            relation_digest: digest(20),
            warp_index_digest: digest(30),
            terminal_index_digest: digest(40),
            verifier_component_digest: digest(50),
            input_arity: 8,
            recursive_app_vk_commit: VkCommit {
                cached_commit: digest(65),
                vk_pre_hash: digest(70),
            },
        }
    }

    fn record() -> ReducedSwirlWrapperRecord {
        let binding = binding();
        ReducedSwirlWrapperRecord {
            statement: ReducedSwirlWrapperStatement {
                protocol_version: binding.protocol_version,
                protocol_digest: binding.protocol_digest,
                relation_digest: binding.relation_digest,
                warp_index_digest: binding.warp_index_digest,
                terminal_index_digest: binding.terminal_index_digest,
                verifier_component_digest: binding.verifier_component_digest,
                schedule_digest: digest(80),
                manifest_digest: digest(90),
                source_count: 9,
                call_count: 2,
                program_commitment: digest(100),
                initial_pc: F::from_u32(4),
                initial_root: digest(110),
                final_pc: F::from_u32(8),
                final_root: digest(120),
                final_accumulator_digest: digest(130),
                final_accumulator_root: digest(140),
            },
        }
    }

    fn constant<AB: AirBuilder<F = F>>(value: F) -> AB::Expr {
        AB::Expr::from_u32(value.as_canonical_u32())
    }

    fn constant_digest<AB: AirBuilder<F = F>>(value: Digest) -> [AB::Expr; DIGEST_SIZE] {
        value.map(constant::<AB>)
    }

    #[derive(Clone)]
    struct FractionalReceiptAuthorityAir {
        buses: ReducedSwirlWrapperReceiptBuses,
        record: ReducedSwirlWrapperRecord,
    }

    impl BaseAir<F> for FractionalReceiptAuthorityAir {
        fn width(&self) -> usize {
            1
        }
    }
    impl BaseAirWithPublicValues<F> for FractionalReceiptAuthorityAir {}
    impl PartitionedBaseAir<F> for FractionalReceiptAuthorityAir {}

    impl<AB> Air<AB> for FractionalReceiptAuthorityAir
    where
        AB: AirBuilder<F = F> + InteractionBuilder,
        AB::Var: Copy,
    {
        fn eval(&self, builder: &mut AB) {
            let weight = builder.main().row_slice(0).expect("authority row")[0];
            let statement = &self.record.statement;
            self.buses.source.add_key_with_lookups(
                builder,
                ReducedSwirlSourceReceiptMessage {
                    protocol_digest: constant_digest::<AB>(statement.protocol_digest),
                    manifest_digest: constant_digest::<AB>(statement.manifest_digest),
                    source_offset: AB::Expr::ZERO,
                    source_count: AB::Expr::from_u32(statement.source_count),
                    program_commitment: constant_digest::<AB>(statement.program_commitment),
                    initial_pc: constant::<AB>(statement.initial_pc),
                    initial_root: constant_digest::<AB>(statement.initial_root),
                    final_pc: constant::<AB>(statement.final_pc),
                    final_root: constant_digest::<AB>(statement.final_root),
                    exit_code: AB::Expr::ZERO,
                    is_terminate: AB::Expr::ONE,
                },
                weight,
            );
            self.buses.vacc.add_key_with_lookups(
                builder,
                ReducedSwirlVaccReceiptMessage {
                    protocol_digest: constant_digest::<AB>(statement.protocol_digest),
                    relation_digest: constant_digest::<AB>(statement.relation_digest),
                    warp_index_digest: constant_digest::<AB>(statement.warp_index_digest),
                    schedule_digest: constant_digest::<AB>(statement.schedule_digest),
                    manifest_digest: constant_digest::<AB>(statement.manifest_digest),
                    source_count: AB::Expr::from_u32(statement.source_count),
                    call_count: AB::Expr::from_u32(statement.call_count),
                    final_accumulator_digest: constant_digest::<AB>(
                        statement.final_accumulator_digest,
                    ),
                    final_accumulator_root: constant_digest::<AB>(statement.final_accumulator_root),
                },
                weight,
            );
            self.buses.terminal.add_key_with_lookups(
                builder,
                ReducedSwirlTerminalReceiptMessage {
                    protocol_digest: constant_digest::<AB>(statement.protocol_digest),
                    relation_digest: constant_digest::<AB>(statement.relation_digest),
                    terminal_index_digest: constant_digest::<AB>(statement.terminal_index_digest),
                    verifier_component_digest: constant_digest::<AB>(
                        statement.verifier_component_digest,
                    ),
                    final_accumulator_digest: constant_digest::<AB>(
                        statement.final_accumulator_digest,
                    ),
                    final_accumulator_root: constant_digest::<AB>(statement.final_accumulator_root),
                },
                weight,
            );
        }
    }

    #[derive(Clone)]
    struct Components {
        buses: ReducedSwirlWrapperReceiptBuses,
        digest: Digest,
        record: ReducedSwirlWrapperRecord,
    }

    impl ReducedSwirlWrapperVerifierComponents for Components {
        fn receipt_buses(&self) -> ReducedSwirlWrapperReceiptBuses {
            self.buses
        }

        fn component_digest(&self) -> Digest {
            self.digest
        }

        fn component_air_count(&self) -> usize {
            1
        }

        fn airs<Config: StarkProtocolConfig<F = F>>(&self) -> Vec<AirRef<Config>> {
            vec![Arc::new(FractionalReceiptAuthorityAir {
                buses: self.buses,
                record: self.record.clone(),
            })]
        }
    }

    fn system() -> Arc<ReducedSwirlWrapperCudaSystem<Components>> {
        let binding = binding();
        Arc::new(
            ReducedSwirlWrapperCudaSystem::new_with_component_air_profile(
                binding.clone(),
                Arc::new(Components {
                    buses: ReducedSwirlWrapperReceiptBuses::new(1_100),
                    digest: binding.verifier_component_digest,
                    record: record(),
                }),
                SystemParams::new_for_testing(8),
                vec![0, 0],
            )
            .expect("CUDA wrapper system"),
        )
    }

    fn cpu_context(weight: F) -> AirProvingContext<CpuBackend<SC>> {
        AirProvingContext::simple_no_pis(RowMajorMatrix::new(vec![weight, weight], 1))
    }

    #[test]
    fn component_slot_profile_is_setup_fixed_and_covers_every_relation() {
        let binding = binding();
        let components = Arc::new(Components {
            buses: ReducedSwirlWrapperReceiptBuses::new(1_100),
            digest: binding.verifier_component_digest,
            record: record(),
        });
        let params = SystemParams::new_for_testing(8);
        let canonical = ReducedSwirlWrapperCudaSystem::new(
            binding.clone(),
            Arc::clone(&components),
            params.clone(),
        )
        .expect("canonical component profile");
        assert_eq!(canonical.component_air_profile(), [0]);

        assert!(matches!(
            ReducedSwirlWrapperCudaSystem::new_with_component_air_profile(
                binding,
                components,
                params,
                Vec::new(),
            ),
            Err(ReducedSwirlWrapperSystemError::KeyIntegrity(
                "component AIR profile"
            ))
        ));
    }

    #[test]
    fn repeated_air_ids_are_accepted_but_coverage_and_shape_are_exact() {
        let system = system();
        let quarter = F::from_u32(4).inverse();
        let repeated = vec![(0, cpu_context(quarter)), (0, cpu_context(quarter))];
        validate_component_contexts(system.as_ref(), &repeated).expect("repeated component AIR ID");

        assert!(matches!(
            validate_component_contexts::<_, CpuBackend<SC>>(system.as_ref(), &[]),
            Err(ReducedSwirlWrapperSystemError::Context(
                "component AIR multiplicity profile"
            ))
        ));
        assert!(matches!(
            validate_component_contexts(system.as_ref(), &[(1, cpu_context(quarter))]),
            Err(ReducedSwirlWrapperSystemError::Context("AIR index"))
        ));
        let malformed: AirProvingContext<CpuBackend<SC>> =
            AirProvingContext::simple_no_pis(RowMajorMatrix::new(vec![quarter; 4], 2));
        assert!(matches!(
            validate_component_contexts(system.as_ref(), &[(0, malformed)]),
            Err(ReducedSwirlWrapperSystemError::Context("trace shape"))
        ));
    }

    #[test]
    fn repeated_component_cuda_proof_cpu_verifies() {
        let system = system();
        let mut prover = ReducedSwirlWrapperCudaProver::new(system).expect("CUDA wrapper prover");
        assert!(prover
            .keys()
            .verifying_key
            .inner
            .per_air
            .iter()
            .all(|air| air.is_required));
        assert_eq!(prover.keys().component_air_profile(), [0, 0]);

        let mut wrong_profile = prover.keys().clone();
        wrong_profile.component_air_profile.pop();
        assert!(matches!(
            validate_keys(prover.system.as_ref(), &wrong_profile),
            Err(ReducedSwirlWrapperSystemError::KeyIntegrity("wrapper key"))
        ));

        let mut corrupt_pre_hash = prover.keys().clone();
        Arc::make_mut(&mut corrupt_pre_hash.verifying_key).pre_hash[0] += F::ONE;
        assert!(matches!(
            validate_keys(prover.system.as_ref(), &corrupt_pre_hash),
            Err(ReducedSwirlWrapperSystemError::KeyIntegrity("wrapper key"))
        ));

        let quarter = F::from_u32(4).inverse();
        let transported = transport_reduced_swirl_wrapper_witness_to_cuda(
            prover.device(),
            ReducedSwirlWrapperWitness {
                component_contexts: vec![(0, cpu_context(quarter)), (0, cpu_context(quarter))],
            },
        )
        .expect("single-pass CPU-to-CUDA wrapper transport");
        validate_component_contexts(prover.system.as_ref(), &transported.component_contexts)
            .expect("transported wrapper contexts");
        let record = record();
        let proof = prover
            .prove(&record, transported)
            .expect("CUDA wrapper proof with repeated AIR contexts");
        prover
            .verify(&record, &proof)
            .expect("ordinary CPU wrapper verification");
        assert_eq!(proof.public_values.len(), 5);

        let mut wrong_public_record = record;
        wrong_public_record.statement.final_pc += F::ONE;
        assert!(matches!(
            prover.verify(&wrong_public_record, &proof),
            Err(ReducedSwirlWrapperSystemError::PublicValues)
        ));
    }
}
