use core::borrow::{Borrow, BorrowMut};
use std::sync::Arc;

use openvm_circuit_primitives::{
    utils::assert_array_eq, ColumnsAir, StructReflection, StructReflectionHelper,
};
use openvm_recursion_circuit_derive::AlignedBorrow;
use openvm_stark_backend::{
    interaction::InteractionBuilder,
    native_warp::NativeWarpChallenger,
    transcript::{TranscriptHistory, TranscriptLog},
    warp_accum::{
        terminal_whir::observe_terminal_whir_layout_binding, TerminalConstrainedRsStatement,
        TerminalDescriptor, TerminalWhirVerification, WhirInitialRsLayout, WhirInitialRsWarpCode,
    },
    warp_pesat::TerminalWeightSpec,
    BaseAirWithPublicValues, FiatShamirTranscript, PartitionedBaseAir, StarkProtocolConfig,
    WhirConfig,
};
use openvm_stark_sdk::config::baby_bear_poseidon2::{
    default_duplex_sponge_recorder, BabyBearPoseidon2Config as SC, Digest, DIGEST_SIZE, D_EF, EF, F,
};
use p3_air::{Air, AirBuilder, BaseAir};
use p3_field::{extension::BinomiallyExtendable, BasedVectorSpace, PrimeCharacteristicRing};
use p3_matrix::{dense::RowMajorMatrix, Matrix};

use crate::{
    bus::TranscriptBus,
    native_warp::terminal::{
        NativeTerminalAccumulatorValueBus, NativeTerminalAccumulatorValueMessage,
        NativeTerminalLinearizerEndBus, NativeTerminalLinearizerEndMessage,
        NativeTerminalWhirLinearizerWeightBus, NativeTerminalWhirLinearizerWeightMessage,
        NativeTerminalWhirPointBus, NativeTerminalWhirPointMessage, NativeTerminalWhirStatementBus,
        NativeTerminalWhirStatementMessage,
    },
    utils::ext_field_multiply,
};

pub const NATIVE_TERMINAL_DESCRIPTOR_DOMAIN_TAG: u64 = 917_001;

/// Setup-fixed observations between the dynamic terminal root and the first
/// terminal-WHIR challenge.
///
/// The values are generated by the backend's own
/// [`TerminalDescriptor::observe_fiat_shamir`] and
/// [`observe_terminal_whir_layout_binding`] implementations.  In particular,
/// coefficient-native layouts retain both byte encodings; callers cannot
/// substitute `TerminalDescriptor::metadata_words()`, whose field-word image
/// is not the Fiat--Shamir byte image.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct NativeTerminalTranscriptBinding {
    layout: WhirInitialRsLayout,
    descriptor_post_root: Arc<[F]>,
    whir_layout: Arc<[F]>,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum NativeTerminalTranscriptBindingError {
    Descriptor,
    Layout,
    Transcript,
}

impl NativeTerminalTranscriptBinding {
    /// Construct the exact binding used by the coefficient-native SWIRL
    /// terminal. Ordinary-subgroup layouts are rejected: this module
    /// certifies the reduced-SWIRL Eq relation and accepts only the
    /// coefficient-subgroup layout.
    pub fn coefficient_subgroup<Obs>(
        descriptor: &TerminalDescriptor<Digest>,
        code: &WhirInitialRsWarpCode<<SC as StarkProtocolConfig>::Hasher, Obs>,
        whir: &WhirConfig,
    ) -> Result<Self, NativeTerminalTranscriptBindingError> {
        if code.layout() != WhirInitialRsLayout::CoefficientSubgroup {
            return Err(NativeTerminalTranscriptBindingError::Layout);
        }
        descriptor
            .validate_whir_initial_rs::<<SC as StarkProtocolConfig>::Hasher, Obs>(
                &descriptor.root,
                code,
                whir,
                D_EF,
            )
            .map_err(|_| NativeTerminalTranscriptBindingError::Descriptor)?;

        let mut challenger = NativeWarpChallenger::<SC, _>::new(default_duplex_sponge_recorder());
        descriptor.observe_fiat_shamir::<SC, _>(&mut challenger);
        let descriptor_end = challenger
            .history_checkpoint()
            .ok_or(NativeTerminalTranscriptBindingError::Transcript)?;
        observe_terminal_whir_layout_binding::<SC, Obs, _>(code, &mut challenger)
            .map_err(|_| NativeTerminalTranscriptBindingError::Layout)?;
        let transcript_end = challenger
            .history_checkpoint()
            .ok_or(NativeTerminalTranscriptBindingError::Transcript)?;
        let log = TranscriptHistory::into_log(challenger.into_inner());

        let root_end = 1usize
            .checked_add(DIGEST_SIZE)
            .ok_or(NativeTerminalTranscriptBindingError::Transcript)?;
        if descriptor_end.operations < root_end
            || transcript_end.operations < descriptor_end.operations
            || log.values().len() != transcript_end.operations
            || log.samples().iter().any(|&sample| sample)
            || log.values().first() != Some(&F::from_u64(NATIVE_TERMINAL_DESCRIPTOR_DOMAIN_TAG))
            || log.values().get(1..root_end) != Some(descriptor.root.as_slice())
        {
            return Err(NativeTerminalTranscriptBindingError::Transcript);
        }
        let descriptor_post_root = log
            .values()
            .get(root_end..descriptor_end.operations)
            .ok_or(NativeTerminalTranscriptBindingError::Transcript)?
            .to_vec();
        let whir_layout = log
            .values()
            .get(descriptor_end.operations..transcript_end.operations)
            .ok_or(NativeTerminalTranscriptBindingError::Transcript)?
            .to_vec();
        if whir_layout.is_empty() {
            return Err(NativeTerminalTranscriptBindingError::Layout);
        }
        Ok(Self {
            layout: code.layout(),
            descriptor_post_root: descriptor_post_root.into(),
            whir_layout: whir_layout.into(),
        })
    }

    #[must_use]
    pub const fn layout(&self) -> WhirInitialRsLayout {
        self.layout
    }

    pub fn descriptor_post_root(&self) -> &[F] {
        &self.descriptor_post_root
    }

    pub fn whir_layout(&self) -> &[F] {
        &self.whir_layout
    }

    #[must_use]
    pub fn whir_post_root_len(&self) -> usize {
        self.descriptor_post_root.len() + self.whir_layout.len()
    }

    fn whir_post_root(&self) -> impl Iterator<Item = F> + '_ {
        self.descriptor_post_root
            .iter()
            .chain(self.whir_layout.iter())
            .copied()
    }
}

/// The sole nonlinear terminal claim for reduced SWIRL WARP is
/// `P(beta, message) = target`, represented by one Eq weight.  The last
/// normalized beta coordinate stores the source target and WARP's accumulated
/// residual is added back exactly as required by the reduced-code adapter.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct NativeTerminalEqClaim {
    pub point: Vec<EF>,
    pub target: EF,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum NativeTerminalEqClaimError {
    Shape,
    Relation,
}

pub fn native_terminal_eq_claim(
    normalized_beta: &[EF],
    accumulated_eta: EF,
) -> Result<NativeTerminalEqClaim, NativeTerminalEqClaimError> {
    let (&source_target, point) = normalized_beta
        .split_last()
        .ok_or(NativeTerminalEqClaimError::Shape)?;
    if point.is_empty() {
        return Err(NativeTerminalEqClaimError::Shape);
    }
    Ok(NativeTerminalEqClaim {
        point: point.to_vec(),
        target: source_target + accumulated_eta,
    })
}

pub fn validate_native_terminal_eq_statement(
    normalized_beta: &[EF],
    accumulated_eta: EF,
    statement: &TerminalConstrainedRsStatement<EF>,
) -> Result<NativeTerminalEqClaim, NativeTerminalEqClaimError> {
    let expected = native_terminal_eq_claim(normalized_beta, accumulated_eta)?;
    let [claim] = statement.linearizer_claims.as_slice() else {
        return Err(NativeTerminalEqClaimError::Relation);
    };
    match &claim.weight {
        TerminalWeightSpec::Eq { point }
            if point == &expected.point && claim.target == expected.target =>
        {
            Ok(expected)
        }
        TerminalWeightSpec::Eq { .. } | TerminalWeightSpec::PrismalinearMappedColumns(_) => {
            Err(NativeTerminalEqClaimError::Relation)
        }
    }
}

#[repr(C)]
#[derive(AlignedBorrow, StructReflection)]
pub struct NativeTerminalWhirStatementCols<T> {
    pub active: T,
    pub tidx: T,
    pub root: [T; DIGEST_SIZE],
    pub mu: [T; D_EF],
    pub beta_last: [T; D_EF],
    pub eta: [T; D_EF],
    pub batching_challenge: [T; D_EF],
    pub initial_claim: [T; D_EF],
}

/// Replays the base-field terminal descriptor, samples `xi`, and constructs
/// `mu + xi * (eta + beta_last)`.
#[derive(ColumnsAir)]
#[columns_via(NativeTerminalWhirStatementCols<u8>)]
pub struct NativeTerminalWhirStatementAir {
    pub transcript_bus: TranscriptBus,
    pub linearizer_end_bus: NativeTerminalLinearizerEndBus,
    pub statement_bus: NativeTerminalWhirStatementBus,
    pub transcript_binding: Arc<NativeTerminalTranscriptBinding>,
}

impl BaseAirWithPublicValues<F> for NativeTerminalWhirStatementAir {}
impl PartitionedBaseAir<F> for NativeTerminalWhirStatementAir {}
impl BaseAir<F> for NativeTerminalWhirStatementAir {
    fn width(&self) -> usize {
        NativeTerminalWhirStatementCols::<F>::width()
    }
}

impl<AB: AirBuilder<F = F> + InteractionBuilder> Air<AB> for NativeTerminalWhirStatementAir
where
    <AB::Expr as PrimeCharacteristicRing>::PrimeSubfield: BinomiallyExtendable<{ D_EF }>,
{
    fn eval(&self, builder: &mut AB) {
        let main = builder.main();
        let row = main
            .row_slice(0)
            .expect("native terminal WHIR statement row");
        let local: &NativeTerminalWhirStatementCols<AB::Var> = (*row).borrow();
        builder.assert_bool(local.active);
        builder.when_first_row().assert_one(local.active);
        builder.when_transition().assert_zero(local.active);

        self.linearizer_end_bus.receive(
            builder,
            NativeTerminalLinearizerEndMessage {
                tidx: local.tidx.into(),
                root: local.root.map(Into::into),
                mu: local.mu.map(Into::into),
                beta_last: local.beta_last.map(Into::into),
                eta: local.eta.map(Into::into),
            },
            local.active,
        );
        self.transcript_bus.observe(
            builder,
            AB::Expr::ZERO,
            local.tidx.into(),
            AB::Expr::from_u64(NATIVE_TERMINAL_DESCRIPTOR_DOMAIN_TAG),
            local.active,
        );
        self.transcript_bus.observe_commit(
            builder,
            AB::Expr::ZERO,
            AB::Expr::from(local.tidx) + AB::Expr::ONE,
            local.root,
            local.active,
        );
        let metadata_tidx = AB::Expr::from(local.tidx) + AB::Expr::from_usize(1 + DIGEST_SIZE);
        for (index, value) in self.transcript_binding.whir_post_root().enumerate() {
            self.transcript_bus.observe(
                builder,
                AB::Expr::ZERO,
                metadata_tidx.clone() + AB::Expr::from_usize(index),
                AB::Expr::from(value),
                local.active,
            );
        }
        let batching_tidx =
            metadata_tidx + AB::Expr::from_usize(self.transcript_binding.whir_post_root_len());
        self.transcript_bus.sample_ext(
            builder,
            AB::Expr::ZERO,
            batching_tidx.clone(),
            local.batching_challenge,
            local.active,
        );
        let target = core::array::from_fn(|limb| {
            AB::Expr::from(local.eta[limb]) + AB::Expr::from(local.beta_last[limb])
        });
        assert_array_eq(&mut builder.when(local.active), local.initial_claim, {
            let product = ext_field_multiply::<AB::Expr>(local.batching_challenge, target);
            core::array::from_fn(|limb| AB::Expr::from(local.mu[limb]) + product[limb].clone())
        });
        self.statement_bus.add_key_with_lookups(
            builder,
            NativeTerminalWhirStatementMessage {
                tidx: batching_tidx + AB::Expr::from_usize(D_EF),
                root: local.root.map(Into::into),
                batching_challenge: local.batching_challenge.map(Into::into),
                initial_claim: local.initial_claim.map(Into::into),
            },
            local.active * AB::Expr::TWO,
        );
    }
}

#[repr(C)]
#[derive(AlignedBorrow, StructReflection)]
pub struct NativeTerminalWhirLinearizerWeightCols<T> {
    pub active: T,
    pub coordinate: T,
    pub is_first: T,
    pub is_last: T,
    pub statement_tidx: T,
    pub root: [T; DIGEST_SIZE],
    pub batching_challenge: [T; D_EF],
    pub initial_claim: [T; D_EF],
    pub beta: [T; D_EF],
    pub point: [T; D_EF],
    pub factor: [T; D_EF],
    pub product_before: [T; D_EF],
    pub product_after: [T; D_EF],
}

#[derive(ColumnsAir)]
#[columns_via(NativeTerminalWhirLinearizerWeightCols<u8>)]
pub struct NativeTerminalWhirLinearizerWeightAir {
    pub statement_bus: NativeTerminalWhirStatementBus,
    pub accumulator_value_bus: NativeTerminalAccumulatorValueBus,
    pub point_bus: NativeTerminalWhirPointBus,
    pub output_bus: NativeTerminalWhirLinearizerWeightBus,
    pub log_message_len: usize,
}

impl BaseAirWithPublicValues<F> for NativeTerminalWhirLinearizerWeightAir {}
impl PartitionedBaseAir<F> for NativeTerminalWhirLinearizerWeightAir {}
impl BaseAir<F> for NativeTerminalWhirLinearizerWeightAir {
    fn width(&self) -> usize {
        NativeTerminalWhirLinearizerWeightCols::<F>::width()
    }
}

impl<AB: AirBuilder<F = F> + InteractionBuilder> Air<AB> for NativeTerminalWhirLinearizerWeightAir
where
    <AB::Expr as PrimeCharacteristicRing>::PrimeSubfield: BinomiallyExtendable<{ D_EF }>,
{
    fn eval(&self, builder: &mut AB) {
        let main = builder.main();
        let local_row = main
            .row_slice(0)
            .expect("native terminal linearizer weight row");
        let next_row = main
            .row_slice(1)
            .expect("native terminal next linearizer weight row");
        let local: &NativeTerminalWhirLinearizerWeightCols<AB::Var> = (*local_row).borrow();
        let next: &NativeTerminalWhirLinearizerWeightCols<AB::Var> = (*next_row).borrow();

        for flag in [local.active, local.is_first, local.is_last] {
            builder.assert_bool(flag);
        }
        builder.when_first_row().assert_one(local.active);
        builder.when_first_row().assert_one(local.is_first);
        builder.when_first_row().assert_zero(local.coordinate);
        builder.when(local.active * local.is_last).assert_eq(
            local.coordinate,
            AB::Expr::from_usize(self.log_message_len - 1),
        );
        builder
            .when_transition()
            .assert_bool(local.active - next.active);
        builder
            .when_transition()
            .assert_eq(local.active - next.active, local.is_last);
        let mut transition = builder.when_transition();
        let mut same = transition.when(next.active);
        same.assert_zero(next.is_first);
        same.assert_eq(next.coordinate, local.coordinate + AB::F::ONE);
        same.assert_eq(next.statement_tidx, local.statement_tidx);
        assert_array_eq(&mut same, next.root, local.root);
        assert_array_eq(&mut same, next.batching_challenge, local.batching_challenge);
        assert_array_eq(&mut same, next.initial_claim, local.initial_claim);
        assert_array_eq(&mut same, next.product_before, local.product_after);
        builder
            .when_last_row()
            .assert_eq(local.is_last, local.active);

        self.statement_bus.lookup_key(
            builder,
            NativeTerminalWhirStatementMessage {
                tidx: local.statement_tidx.into(),
                root: local.root.map(Into::into),
                batching_challenge: local.batching_challenge.map(Into::into),
                initial_claim: local.initial_claim.map(Into::into),
            },
            local.active * local.is_first,
        );
        self.accumulator_value_bus.lookup_key(
            builder,
            NativeTerminalAccumulatorValueMessage {
                section: AB::Expr::from_usize(2),
                coordinate: AB::Expr::from_usize(self.log_message_len - 1) - local.coordinate,
                value: local.beta.map(Into::into),
            },
            local.active,
        );
        self.point_bus.lookup_key(
            builder,
            NativeTerminalWhirPointMessage {
                coordinate: local.coordinate.into(),
                value: local.point.map(Into::into),
            },
            local.active,
        );
        let one = core::array::from_fn(|limb| {
            if limb == 0 {
                AB::Expr::ONE
            } else {
                AB::Expr::ZERO
            }
        });
        assert_array_eq(
            &mut builder.when(local.active * local.is_first),
            local.product_before,
            one.clone(),
        );
        let point_beta = ext_field_multiply::<AB::Expr>(local.point, local.beta);
        let expected_factor = core::array::from_fn(|limb| {
            one[limb].clone()
                - AB::Expr::from(local.point[limb])
                - AB::Expr::TWO * AB::Expr::from(local.beta[limb])
                + AB::Expr::from_usize(3) * point_beta[limb].clone()
        });
        assert_array_eq(
            &mut builder.when(local.active),
            local.factor,
            expected_factor,
        );
        assert_array_eq(
            &mut builder.when(local.active),
            local.product_after,
            ext_field_multiply::<AB::Expr>(local.product_before, local.factor),
        );
        self.output_bus.send(
            builder,
            NativeTerminalWhirLinearizerWeightMessage {
                value: ext_field_multiply::<AB::Expr>(
                    local.batching_challenge,
                    local.product_after,
                ),
            },
            local.active * local.is_last,
        );
    }
}

pub fn generate_native_terminal_whir_statement_trace(
    descriptor: &TerminalDescriptor<Digest>,
    transcript_binding: &NativeTerminalTranscriptBinding,
    mu: EF,
    beta_last: EF,
    eta: EF,
    verification: &TerminalWhirVerification<F, EF, Digest>,
    transcript: &TranscriptLog<F, [F; 16]>,
) -> Option<RowMajorMatrix<F>> {
    if transcript_binding.layout() != WhirInitialRsLayout::CoefficientSubgroup
        || verification.root != descriptor.root
        || verification.initial_claim != mu + verification.batching_challenge * (eta + beta_last)
    {
        return None;
    }
    let tidx = verification.transcript_start.operations;
    let metadata_len = transcript_binding.whir_post_root_len();
    let batching_tidx = tidx.checked_add(1 + DIGEST_SIZE + metadata_len)?;
    if verification.descriptor_span.start.operations != tidx
        || verification.descriptor_span.end.operations != batching_tidx
        || verification.batching_challenge_span.start.operations != batching_tidx
        || verification.batching_challenge_span.end.operations != batching_tidx + D_EF
        || transcript.values().get(tidx)? != &F::from_u64(NATIVE_TERMINAL_DESCRIPTOR_DOMAIN_TAG)
    {
        return None;
    }
    let root_start = tidx.checked_add(1)?;
    let root_end = root_start.checked_add(DIGEST_SIZE)?;
    if transcript.values().get(root_start..root_end)? != descriptor.root.as_slice()
        || transcript
            .samples()
            .get(tidx..batching_tidx)?
            .iter()
            .any(|&sample| sample)
        || transcript
            .values()
            .get(root_end..batching_tidx)?
            .iter()
            .copied()
            .ne(transcript_binding.whir_post_root())
        || transcript
            .values()
            .get(batching_tidx..batching_tidx + D_EF)?
            != verification
                .batching_challenge
                .as_basis_coefficients_slice()
        || transcript
            .samples()
            .get(batching_tidx..batching_tidx + D_EF)?
            .iter()
            .any(|&sample| !sample)
    {
        return None;
    }
    let width = NativeTerminalWhirStatementCols::<F>::width();
    let mut values = F::zero_vec(width);
    let cols: &mut NativeTerminalWhirStatementCols<F> = values.as_mut_slice().borrow_mut();
    cols.active = F::ONE;
    cols.tidx = F::from_usize(tidx);
    cols.root = descriptor.root;
    copy_ext(&mut cols.mu, mu);
    copy_ext(&mut cols.beta_last, beta_last);
    copy_ext(&mut cols.eta, eta);
    copy_ext(
        &mut cols.batching_challenge,
        verification.batching_challenge,
    );
    copy_ext(&mut cols.initial_claim, verification.initial_claim);
    Some(RowMajorMatrix::new(values, width))
}

pub fn generate_native_terminal_whir_linearizer_weight_trace(
    beta: &[EF],
    verification: &TerminalWhirVerification<F, EF, Digest>,
    required_height: Option<usize>,
) -> Option<RowMajorMatrix<F>> {
    let log_message_len = beta.len().checked_sub(1)?;
    let mut point = verification
        .rounds
        .iter()
        .flat_map(|round| round.alphas.iter().copied())
        .collect::<Vec<_>>();
    point.extend_from_slice(&verification.suffix_point);
    if point.len() != log_message_len || log_message_len == 0 {
        return None;
    }
    let height = required_height.unwrap_or_else(|| log_message_len.next_power_of_two());
    if height < log_message_len {
        return None;
    }
    let width = NativeTerminalWhirLinearizerWeightCols::<F>::width();
    let mut values = F::zero_vec(height * width);
    let mut product = EF::ONE;
    let statement_tidx = verification.batching_challenge_span.end.operations;
    for (coordinate, &point_value) in point.iter().enumerate() {
        let beta_value = beta[log_message_len - 1 - coordinate];
        let factor =
            (EF::ONE - point_value) * (EF::ONE - beta_value.double()) + point_value * beta_value;
        let product_after = product * factor;
        let row = &mut values[coordinate * width..(coordinate + 1) * width];
        let cols: &mut NativeTerminalWhirLinearizerWeightCols<F> = row.borrow_mut();
        cols.active = F::ONE;
        cols.coordinate = F::from_usize(coordinate);
        cols.is_first = F::from_bool(coordinate == 0);
        cols.is_last = F::from_bool(coordinate + 1 == log_message_len);
        cols.statement_tidx = F::from_usize(statement_tidx);
        cols.root = verification.root;
        copy_ext(
            &mut cols.batching_challenge,
            verification.batching_challenge,
        );
        copy_ext(&mut cols.initial_claim, verification.initial_claim);
        copy_ext(&mut cols.beta, beta_value);
        copy_ext(&mut cols.point, point_value);
        copy_ext(&mut cols.factor, factor);
        copy_ext(&mut cols.product_before, product);
        copy_ext(&mut cols.product_after, product_after);
        product = product_after;
    }
    Some(RowMajorMatrix::new(values, width))
}

fn copy_ext(target: &mut [F; D_EF], value: EF) {
    target.copy_from_slice(value.as_basis_coefficients_slice());
}

const _: () = assert!(D_EF == 4);

#[cfg(test)]
mod tests {
    use openvm_stark_backend::{
        transcript::TranscriptCheckpoint,
        warp_accum::{
            rs_whir::COEFFICIENT_SUBGROUP_RS_LAYOUT_TAG,
            terminal_whir::{TerminalWhirTranscriptPhase, TerminalWhirTranscriptPhaseSpan},
            RsAdjointEvalVerification,
        },
        warp_pesat::{PrismalinearMappedColumnWeight, TerminalStructuredLinearClaim},
        WhirProximityStrategy, WhirRoundConfig,
    };

    use super::*;

    fn whir() -> WhirConfig {
        WhirConfig {
            k: 4,
            rounds: vec![WhirRoundConfig { num_queries: 1 }],
            mu_pow_bits: 0,
            query_phase_pow_bits: 0,
            folding_pow_bits: 0,
            proximity: WhirProximityStrategy::UniqueDecoding,
        }
    }

    fn coefficient_code() -> WhirInitialRsWarpCode<<SC as StarkProtocolConfig>::Hasher> {
        let config =
            SC::default_from_params(openvm_stark_backend::SystemParams::new_for_testing(8));
        WhirInitialRsWarpCode::try_new_coefficient_subgroup(config.hasher().clone(), 8, 1, 0, 16)
            .expect("coefficient-subgroup fixture")
    }

    fn checkpoint(operations: usize) -> TranscriptCheckpoint {
        TranscriptCheckpoint {
            operations,
            events: 0,
            permutations: 0,
        }
    }

    fn span(
        phase: TerminalWhirTranscriptPhase,
        start: usize,
        end: usize,
    ) -> TerminalWhirTranscriptPhaseSpan {
        TerminalWhirTranscriptPhaseSpan {
            phase,
            start: checkpoint(start),
            end: checkpoint(end),
        }
    }

    fn fake_verification(
        root: Digest,
        start: usize,
        descriptor_end: usize,
        batching_end: usize,
        xi: EF,
        initial_claim: EF,
    ) -> TerminalWhirVerification<F, EF, Digest> {
        TerminalWhirVerification {
            transcript_start: checkpoint(start),
            descriptor_span: span(
                TerminalWhirTranscriptPhase::Descriptor,
                start,
                descriptor_end,
            ),
            batching_challenge_span: span(
                TerminalWhirTranscriptPhase::BatchingChallenge,
                descriptor_end,
                batching_end,
            ),
            transcript_end: checkpoint(batching_end),
            root,
            batching_challenge: xi,
            initial_claim,
            rounds: Vec::new(),
            final_poly: Vec::new(),
            final_weight_evals: Vec::new(),
            final_weight_span: span(
                TerminalWhirTranscriptPhase::FinalWeight,
                batching_end,
                batching_end,
            ),
            suffix_point: Vec::new(),
            accumulator_adjoint: RsAdjointEvalVerification {
                transcript_start: checkpoint(batching_end),
                transcript_end: checkpoint(batching_end),
                claimed_value: EF::ZERO,
                degree: 0,
                rounds: Vec::new(),
                point: Vec::new(),
                final_claim: EF::ZERO,
                expected_final: EF::ZERO,
            },
            expected_weight: EF::ZERO,
            actual_weight: EF::ZERO,
            final_inner_product: EF::ZERO,
            final_claim: EF::ZERO,
        }
    }

    #[test]
    fn coefficient_subgroup_binding_replays_backend_bytes_and_rejects_layout_mutations() {
        let code = coefficient_code();
        let whir = whir();
        let root = core::array::from_fn(|index| F::from_usize(100 + index));
        let descriptor = TerminalDescriptor::from_whir_initial_rs(root, &code, &whir, D_EF);
        let binding =
            NativeTerminalTranscriptBinding::coefficient_subgroup(&descriptor, &code, &whir)
                .expect("exact coefficient terminal binding");
        assert_eq!(binding.layout(), WhirInitialRsLayout::CoefficientSubgroup);
        assert!(binding
            .whir_layout()
            .windows(COEFFICIENT_SUBGROUP_RS_LAYOUT_TAG.len())
            .any(|window| {
                window.iter().copied().eq(COEFFICIENT_SUBGROUP_RS_LAYOUT_TAG
                    .iter()
                    .copied()
                    .map(F::from_u8))
            }));
        let metadata_word_image = descriptor
            .metadata_words()
            .map(F::from_u64)
            .collect::<Vec<_>>();
        assert_ne!(binding.descriptor_post_root(), metadata_word_image);

        let mut changed = descriptor.clone();
        changed.code_layout_version ^= 1;
        assert_eq!(
            NativeTerminalTranscriptBinding::coefficient_subgroup(&changed, &code, &whir),
            Err(NativeTerminalTranscriptBindingError::Descriptor),
        );
        let mut changed = descriptor.clone();
        changed.initial_folding_factor = 1;
        assert_eq!(
            NativeTerminalTranscriptBinding::coefficient_subgroup(&changed, &code, &whir),
            Err(NativeTerminalTranscriptBindingError::Descriptor),
        );
        let config =
            SC::default_from_params(openvm_stark_backend::SystemParams::new_for_testing(8));
        let ordinary = WhirInitialRsWarpCode::new(config.hasher().clone(), 8, 1, 0, 16);
        assert_eq!(
            NativeTerminalTranscriptBinding::coefficient_subgroup(&descriptor, &ordinary, &whir,),
            Err(NativeTerminalTranscriptBindingError::Layout),
        );

        // The root is dynamic and therefore deliberately excluded from the
        // setup-fixed tail; it is constrained separately by the root bus.
        let mut changed_root = descriptor;
        changed_root.root[0] += F::ONE;
        let changed_binding =
            NativeTerminalTranscriptBinding::coefficient_subgroup(&changed_root, &code, &whir)
                .expect("dynamic root uses the same setup-fixed tail");
        assert_eq!(binding, changed_binding);
    }

    #[test]
    fn reduced_swirl_terminal_accepts_only_the_exact_eq_claim() {
        let point = vec![EF::from_u64(3), EF::from_u64(5), EF::from_u64(7)];
        let source_target = EF::from_u64(11);
        let eta = EF::from_u64(13);
        let beta = point
            .iter()
            .copied()
            .chain([source_target])
            .collect::<Vec<_>>();
        let statement = TerminalConstrainedRsStatement {
            linearizer_claims: vec![TerminalStructuredLinearClaim::new(
                TerminalWeightSpec::Eq {
                    point: point.clone(),
                },
                source_target + eta,
            )],
        };
        assert_eq!(
            validate_native_terminal_eq_statement(&beta, eta, &statement),
            Ok(NativeTerminalEqClaim {
                point: point.clone(),
                target: source_target + eta,
            }),
        );

        let mut wrong_coordinate = statement.clone();
        if let TerminalWeightSpec::Eq { point } = &mut wrong_coordinate.linearizer_claims[0].weight
        {
            point[1] += EF::ONE;
        } else {
            unreachable!()
        }
        assert_eq!(
            validate_native_terminal_eq_statement(&beta, eta, &wrong_coordinate),
            Err(NativeTerminalEqClaimError::Relation),
        );
        let mut wrong_target = statement.clone();
        wrong_target.linearizer_claims[0].target += EF::ONE;
        assert_eq!(
            validate_native_terminal_eq_statement(&beta, eta, &wrong_target),
            Err(NativeTerminalEqClaimError::Relation),
        );
        let mapped = TerminalConstrainedRsStatement {
            linearizer_claims: vec![TerminalStructuredLinearClaim::new(
                TerminalWeightSpec::PrismalinearMappedColumns(PrismalinearMappedColumnWeight {
                    log_message_len: beta.len() - 1,
                    terms: Vec::new(),
                }),
                source_target + eta,
            )],
        };
        assert_eq!(
            validate_native_terminal_eq_statement(&beta, eta, &mapped),
            Err(NativeTerminalEqClaimError::Relation),
        );
    }

    #[test]
    fn coefficient_eq_pullback_matches_backend_coordinates() {
        let code = coefficient_code();
        let point = (0..code.log_message_len())
            .map(|index| EF::from_usize(17 + 3 * index))
            .collect::<Vec<_>>();
        let whir_point = (0..code.log_message_len())
            .map(|index| EF::from_usize(43 + 5 * index))
            .collect::<Vec<_>>();
        let xi = EF::from_u64(97);
        let statement = TerminalConstrainedRsStatement {
            linearizer_claims: vec![TerminalStructuredLinearClaim::new(
                TerminalWeightSpec::Eq {
                    point: point.clone(),
                },
                EF::from_u64(101),
            )],
        };
        let backend = statement.batched_linearizer_weight_eval_at(&code, xi, &whir_point);
        let recursive = xi
            * point
                .iter()
                .rev()
                .zip(&whir_point)
                .map(|(&beta, &coordinate)| {
                    EF::ONE - coordinate - beta.double() + EF::from_u64(3) * coordinate * beta
                })
                .product::<EF>();
        assert_eq!(recursive, backend);

        let mut changed = point;
        changed[0] += EF::ONE;
        let changed_statement = TerminalConstrainedRsStatement {
            linearizer_claims: vec![TerminalStructuredLinearClaim::new(
                TerminalWeightSpec::Eq { point: changed },
                EF::from_u64(101),
            )],
        };
        assert_ne!(
            changed_statement.batched_linearizer_weight_eval_at(&code, xi, &whir_point),
            backend,
        );
    }

    #[test]
    fn statement_trace_rejects_wrong_root_binding_coordinate_and_target() {
        let code = coefficient_code();
        let whir = whir();
        let root = core::array::from_fn(|index| F::from_usize(700 + index));
        let descriptor = TerminalDescriptor::from_whir_initial_rs(root, &code, &whir, D_EF);
        let binding =
            NativeTerminalTranscriptBinding::coefficient_subgroup(&descriptor, &code, &whir)
                .expect("coefficient terminal binding");
        let start = 3usize;
        let descriptor_end = start + 1 + DIGEST_SIZE + binding.whir_post_root_len();
        let batching_end = descriptor_end + D_EF;
        let xi = EF::from_u64(109);
        let mu = EF::from_u64(127);
        let beta_last = EF::from_u64(131);
        let eta = EF::from_u64(137);
        let initial_claim = mu + xi * (eta + beta_last);
        let verification =
            fake_verification(root, start, descriptor_end, batching_end, xi, initial_claim);
        let mut transcript = TranscriptLog::default();
        for index in 0..start {
            transcript.push_observe(F::from_usize(900 + index));
        }
        transcript.push_observe(F::from_u64(NATIVE_TERMINAL_DESCRIPTOR_DOMAIN_TAG));
        transcript.extend_observe(&root);
        let post_root = binding.whir_post_root().collect::<Vec<_>>();
        transcript.extend_observe(&post_root);
        transcript.extend_sample(xi.as_basis_coefficients_slice());
        assert!(generate_native_terminal_whir_statement_trace(
            &descriptor,
            &binding,
            mu,
            beta_last,
            eta,
            &verification,
            &transcript,
        )
        .is_some());

        let mut wrong_root = verification.clone();
        wrong_root.root[0] += F::ONE;
        assert!(generate_native_terminal_whir_statement_trace(
            &descriptor,
            &binding,
            mu,
            beta_last,
            eta,
            &wrong_root,
            &transcript,
        )
        .is_none());
        assert!(generate_native_terminal_whir_statement_trace(
            &descriptor,
            &binding,
            mu,
            beta_last,
            eta + EF::ONE,
            &verification,
            &transcript,
        )
        .is_none());

        let mut wrong_binding = transcript.clone();
        wrong_binding.values_mut()[start + 1 + DIGEST_SIZE] += F::ONE;
        assert!(generate_native_terminal_whir_statement_trace(
            &descriptor,
            &binding,
            mu,
            beta_last,
            eta,
            &verification,
            &wrong_binding,
        )
        .is_none());
        let mut wrong_coordinate = transcript;
        wrong_coordinate.values_mut()[descriptor_end - 1] += F::ONE;
        assert!(generate_native_terminal_whir_statement_trace(
            &descriptor,
            &binding,
            mu,
            beta_last,
            eta,
            &verification,
            &wrong_coordinate,
        )
        .is_none());
    }
}
